replicaCount: 1

image:
  repository: mikejoh/argocd-extra-app-info-exporter
  pullPolicy: IfNotPresent
  tag: ""

argocdExtraAppInfoExporterFlags:
  namespace: ""
  interval: 10s
  metrics:
    path: "/metrics"
    listenAddress: "0.0.0.0"
    port: 9999

imagePullSecrets: []
nameOverride: "argocd-extra-app-info-exporter"
fullnameOverride: "argocd-extra-app-info-exporter"

serviceAccount:
  create: true
  annotations: {}
  name: "argocd-extra-app-info-exporter"

serviceMonitor:
  enabled: false
  portname: metrics
  suffix: metrics

prometheusRule:
  enabled: false

podAnnotations: {}

podSecurityContext: {}

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
