apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "argocd-extra-app-info-exporter.fullname" . }}
  labels:
    {{- include "argocd-extra-app-info-exporter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "argocd-extra-app-info-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "argocd-extra-app-info-exporter.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "argocd-extra-app-info-exporter.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          args:
           {{- if .Values.argocdExtraAppInfoExporterFlags.interval }}
            - -interval
            - "{{ .Values.argocdExtraAppInfoExporterFlags.interval }}"
            {{- end }}
            {{- if .Values.argocdExtraAppInfoExporterFlags.metrics.listenAddress }}
            - -metrics-listen-address
            - "{{ .Values.argocdExtraAppInfoExporterFlags.metrics.listenAddress }}:{{ .Values.argocdExtraAppInfoExporterFlags.metrics.port }}"
            {{- end }}
            {{- if .Values.argocdExtraAppInfoExporterFlags.metrics.port }}
            {{- end }}
            {{- if .Values.argocdExtraAppInfoExporterFlags.metrics.path }}
            - -metrics-path
            - "{{ .Values.argocdExtraAppInfoExporterFlags.metrics.path }}"
            {{- end }}
            {{- if .Values.argocdExtraAppInfoExporterFlags.namespace }}
            - -namespace
            - "{{ .Values.argocdExtraAppInfoExporterFlags.namespace }}"
            {{- end }}
            {{- if .Values.argocdExtraAppInfoExporterFlags.excludeRevisions }}
            - -exclude-revisions
            - "{{ .Values.argocdExtraAppInfoExporterFlags.excludeRevisions | join "," }}"
            {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          ports:
          - containerPort: {{ .Values.argocdExtraAppInfoExporterFlags.metrics.port }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
