{{ if .Values.serviceMonitor.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "argocd-extra-app-info-exporter.name" . }}-metrics
  labels:
    {{- include "argocd-extra-app-info-exporter.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.argocdExtraAppInfoExporterFlags.metrics.port }}
      name: metrics
  selector:
    {{- include "argocd-extra-app-info-exporter.selectorLabels" . | nindent 4 }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "argocd-extra-app-info-exporter.name" . }}
  labels:
    {{- include "argocd-extra-app-info-exporter.labels" . | nindent 4 }}
spec:
  endpoints:
    - interval: 15s
      path: /metrics
      port: {{ .Values.serviceMonitor.portname }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "argocd-extra-app-info-exporter.selectorLabels" . | nindent 6 }}
{{ end }}
